version: '2.2'
services:
  integration-api:
    container_name: integration-api
    env_file:
        - ./integration-api/.env
    build:
        dockerfile: Dockerfile
        context: ./integration-api
    ports:
        - "${INTEGRATION_API_PORT}:${INTEGRATION_API_LOCAL_PORT}"
    volumes:
        - "./integration-api:/usr/src/app"
    depends_on:
      - main-api
    restart: always
    networks:
        - elastic

  main-api:
    container_name: main-api
    env_file:
        - ./main-api/.env
    build:
        dockerfile: Dockerfile
        context: ./main-api
    ports:
        - "${MAIN_API_PORT}:${MAIN_API_LOCAL_PORT}"
    volumes:
        - "./main-api:/usr/src/app"
    #depends_on:
      #- main-api
    restart: always
    networks:
        - elastic
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: 'http://es01:9200'
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200"]'
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge